// mypages.js
// 2023-03-06: by jmm


exports.genMainPage = function(data){
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <title>Página Principal</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="./w3.css"> 
        <style>
            table {
                width: 50%;
            }
            tr {
                height:100px;
                text-align: center;
                font-size: 25px;
            }
        </style>
    </head>
    <body>
        <center>
            <h1>
                Página principal
            </h1>
            <br>
            <br>
            <table border="1">
                <tr>
                    <td>
                        <a href="http://localhost:7777/pessoas">
                            Lista de pessoas
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <a href="http://localhost:7777/pessoasOrd">
                            Lista de pessoas ordenada
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <a href="http://localhost:7777/pessoas/distSexo">
                            Distribuição por Sexo
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <a href="http://localhost:7777/pessoas/distDesporto">
                            Distribuição por Desporto
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <a href="http://localhost:7777/pessoas/distProfissao">
                            Top 10 de profissões
                        </a>
                    </td>
                </tr>
            </table>
        </center>
            
        <footer class="w3-container w3-deep-purple w3-bottom">
            <center>
                <h5>Generated by jmm: ${data}</h5>
            </center>
        </footer>
    </body>
</html>
    `

    return pagHTML
}


exports.genPeoplePage = function(lista, flag, desporto){
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <title>Pessoas</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="./w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>Lista de pessoas ${flag} na Base de Dados</h1>
                <a href="http://localhost:7777/">
                    [Página principal]
                    </a>
            </header>
        </div>
        <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>Sexo</th>
                    <th>Cidade</th>
                </tr>`
            
    for(let i=0; i < lista.length; i++){
        if (desporto == '' || lista[i].desportos.includes(desporto))
        pagHTML += `
        <tr>
                <td>${lista[i].id}</td>
                <td>
                    <a href="http://localhost:7777/pessoas/${lista[i].id}">
                    ${lista[i].nome}
                    </a>
                </td>

                <td>${lista[i].idade}</td>
                <td>${lista[i].sexo}</td>
                <td>${lista[i].morada.cidade}</td>
        </tr>
        `
    }

    pagHTML += `
            </table>
        </div> 
    </body>
</html>
    `

    return pagHTML
}


exports.genPersonPage = function(pessoa){
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <title>${pessoa.nome}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="./w3.css"/> 
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>${pessoa.nome}</h1>
                <a href="http://localhost:7777/">
                    [Página principal]
                </a>
            </header>
        </div>
        <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>Sexo</th>
                    <th>Cidade</th>
                </tr>
            
                <tr>
                    <td>${pessoa.id}</td>
                    <td>${pessoa.nome}</td>
                    <td>${pessoa.idade}</td>
                    <td>${pessoa.sexo}</td>
                    <td>${pessoa.morada.cidade}</td>
                </tr>

            </table>
        </div> 
    </body>
</html>
    `

    return pagHTML
}


exports.genDistPage = function(lista, dist){
    var url;
    var dict = {}
    if (dist == 'Sexo'){
        url = "sexo";
        for(let i=0; i < lista.length; i++){
            if (!(lista[i].sexo in dict)){
                dict[lista[i].sexo] = 0;
            }
            dict[lista[i].sexo]++; 
        }
    }

    else if (dist == 'Desporto'){
        url = "desporto";
        for(let i=0; i < lista.length; i++){
            for(let j=0; j < lista[i].desportos.length; j++){
                if (!(lista[i].desportos[j] in dict))
                    dict[lista[i].desportos[j]] = 0;
                dict[lista[i].desportos[j]]++; 
            }
        } 
    }

    else if (dist == 'Profissao'){
        url = "profissao";
        dist = 'Profissão'
        for(let i=0; i < lista.length; i++){
            if (!(lista[i].profissao in dict)){
                dict[lista[i].profissao] = 0;
            }
            dict[lista[i].profissao]++; 
        }

        var items = Object.keys(dict).map(function(key) {
            return [key, dict[key]];
        });
        items.sort(function(first, second) {
          return second[1] - first[1];
        });
        ten = items.slice(0,10)
        dict = {}
        for(i in ten){
            dict[ten[i][0]] = ten[i][1]
        }
    }

    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <title>${dist}</title>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="./w3.css"/> 
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>Distribuição por ${dist}</h1>
                <a href="http://localhost:7777/">
                    [Página principal]
                </a>
            </header>
        </div>
        <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                    <th>${dist}</th>
                    <th>Frequência</th>
                </tr>`
                
            for(let key in dict) {
                pagHTML += `<tr>
                    <td>${key}</td>
                    <td>
                        <a href="http://localhost:7777/pessoas?${url}=${key}">
                            ${dict[key]}
                        </a>
                    </td>
                </tr>`
            }
    pagHTML +=
            `</table>
        </div> 
    </body>
</html>
    `

    return pagHTML
}